name: Parse Json

inputs:
    path:
        description: Json File Path
        type: string
        required: true

outputs:
    json:
        value: ${{ steps.parse-json.outputs.output }}

runs:
    using: composite
    steps:
        - name: Parse Json
          id: parse-json
          shell: bash
          run: |
              {
                echo "output<<EOF"
                cat ${{ inputs.path }}
                echo "EOF"
              } >> $GITHUB_OUTPUT
