name: Send Announcement to Discord

inputs:
    webhook_url:
        description: Discord Webhook URL
        type: string
        required: true
    avatar_url:
        description: Discord Avatar URL
        type: string
        required: false
        default: https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/apexstudios/Logo.png
    avatar_name:
        description: Discord Sender Name
        type: string
        required: false
        default: ApexStudios

    display_name:
        description: Display Name
        type: string
        required: true
    version:
        description: Release Version Number
        type: string
        required: true
    logo_url:
        description: Logo URL
        type: string
        required: true
    color:
        description: Discord Embed Color
        type: number
        required: false
        default: 0x3C40C7
    build_timestamp:
        description: Build Timestamp
        type: string
        required: true

    curseforge_url:
        description: CurseForge Download URL
        type: string
        required: false
    modrinth_url:
        description: Modrinth Download URL
        type: string
        required: false

runs:
    using: composite
    steps:
        - shell: bash
          run: echo ${{ inputs.color }}
        - name: Send Announcement to Discord
          uses: tsickert/discord-webhook@v6.0.0
          with:
              webhook-url: ${{ inputs.webhook_url }}

              embed-title: ${{ inputs.display_name }} updated to v${{ inputs.version }}!
              embed-thumbnail-url: ${{ inputs.logo_url }}
              embed-color: ${{ inputs.color }}
              embed-timestamp: ${{ inputs.build_timestamp }}

              avatar-url: ${{ inputs.avatar_url }}
              username: ${{ inputs.avatar_name }}
              embed-footer-text: ${{ inputs.avatar_name }}
              embed-footer-icon-url: ${{ inputs.avatar_url }}

#        - name: Send Announcement to Discord (CurseForge Download)
#          uses: tsickert/discord-webhook@v6.0.0
#          if: inputs.curseforge_url
#          with:
#              webhook-url: ${{ inputs.webhook_url }}
#
#              embed-title: Download from [CurseForge](${{ inputs.curseforge_url }})
#              embed-thumbnail-url: https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/third_party/curseforge.png
#              embed-color: 0xEB622B
#
#              avatar-url: ${{ inputs.avatar_url }}
#              username: ${{ inputs.avatar_name }}
#              embed-footer-text: ${{ inputs.avatar_name }}
#              embed-footer-icon-url: ${{ inputs.avatar_url }}

#        - name: Send Announcement to Discord (Modrinth Download)
#          uses: tsickert/discord-webhook@v6.0.0
#          if: inputs.modrinth_url
#          with:
#              webhook-url: ${{ inputs.webhook_url }}
#
#              embed-title: Download from [Modrinth](${{ inputs.modrinth_url }})
#              embed-thumbnail-url: https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/third_party/modrinth.png
#              embed-color: 0x1BD96A
#
#              avatar-url: ${{ inputs.avatar_url }}
#              username: ${{ inputs.avatar_name }}
#              embed-footer-text: ${{ inputs.avatar_name }}
#              embed-footer-icon-url: ${{ inputs.avatar_url }}
