name: Publish to CurseForge

inputs:
  curseforge-id:
    description: CurseForge ID
    required: true
  curseforge-token:
    description: CurseForge Token
    required: true
  display-name:
    description: Display name
    required: true
  artifact-id:
    description: Artifact ID
    required: true
  version:
    description: Version
    required: true
  release-type:
    description: Release type
    required: true

runs:
  using: composite
  steps:
    - name: Publish to CurseForge
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        curseforge-id: ${{ inputs.curseforge-id }}
        curseforge-token: ${{ inputs.curseforge-token }}

        files: ${{ inputs.artifact-id }}-${{ inputs.version }}.jar
        name: ${{ inputs.display-name }}-${{ inputs.version }}
        version: ${{ inputs.version }}
        version-type: release
        changelog: ''
        loaders: neoforge
