name: 💡 Feature Request
description: Suggest an idea for this project.
title: "[Feature Request] "
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submiting this feature request.
  - type: textarea
    id: issue-related
    attributes:
      label: Issue related?
      description: |
        Is your feature request related to a problem? Please describe.

        Please provide as many details as you can.
        A _step by step_ on how to reproduce the issue would also be preferred.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: description
    attributes:
      label: Describe the solution you'd like?
      description: |
        Describe the feature you would like implemented here, in as much detail as you can give.
      placeholder: A clear and concise description of your feature request.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.