name: Checkout Git Repo

outputs:
    version:
        description: Generated version number
        value: ${{ steps.version.outputs.version }}

runs:
    using: composite
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
              fetch-depth: 0
              fetch-tags: true

        - name: Fetch Tags
          if: ${{ !env.ACT }}
          shell: bash
          run: git fetch --tags

        - name: Create branch for PR
          if: github.event_name == 'pull_request'
          shell: bash
          run: git switch -C pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}

        - name: Create branch for Commit
          if: ${{ !env.ACT && github.event_name != 'pull_request' }}
          shell: bash
          run: git switch -C ${{ github.ref_name }}

        - name: Determine version
          uses: paulhatch/semantic-version@v5.4.0
          id: gen_version
          with:
              change_path: "./"
              version_format: "${major}.${minor}.${patch}"
              search_commit_body: true
              bump_each_commit: true

        - name: Output version
          id: version
          shell: bash
          run: |
            if [ $PR_NUM -ge 0 ]; then
              echo version=$VERSION_NUM-beta-pr-${{ github.event.pull_request.number }} >> $GITHUB_OUTPUT
            else
              echo version=$VERSION_NUM >> $GITHUB_OUTPUT
            fi
          env:
            VERSION_NUM: ${{ steps.gen_version.outputs.version }}
            PR_NUM: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || '-1' }}
