name: Checkout repository

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Fetch tags # https://github.com/actions/checkout/issues/2041
      if: ${{ !env.ACT }}
      shell: bash
      run: git fetch --tags

    - name: Create branch for PR
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
      shell: bash
      run: git switch -C pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}

    - name: Create branch for Commit
      if: ${{ !(github.event_name == 'pull_request' || github.event_name == 'pull_request_target') }}
      shell: bash
      run: git switch -C ${{ github.ref_name }}
