name: Generate version

outputs:
  version:
    description: Generated version
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Generate version
      id: version_gen
      uses: paulhatch/semantic-version@v5.4.0
      with:
        change_path: ./
        bump_each_commit: true

    - name: Output version
      id: version
      shell: bash
      run: |
        if [ $RUN_TYPE == "pull_request" || $RUN_TYPE == "pull_request_target" ]; then
          echo version="${{ steps.version_gen.outputs.version }}-beta-pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
        else
          echo version="${{ steps.version_gen.outputs.version }}" >> $GITHUB_OUTPUT
        fi
      env:
        RUN_TYPE: ${{ github.event_name }}
