name: Setup Java

inputs:
    version:
        description: Java Version
        type: string
        required: false
        default: 17
    vendor:
        description: Java Vendor
        type: string
        required: false
        default: temurin

runs:
    using: composite
    steps:
        - name: Setup Java (${{ inputs.vendor }}-${{ inputs.version }})
          uses: actions/setup-java@v4
          with:
              java-version: ${{ inputs.version }}
              distribution: ${{ inputs.vendor }}
