name: Setup Gradle

inputs:
  use-gradle-cache:
    required: false
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-disabled: ${{ !inputs.use-gradle-cache }}
        cache-read-only: ${{ !inputs.use-gradle-cache }}

    - name: Mark Gradle as Executable
      shell: bash
      run: chmod +x gradlew
