name: Setup Gradle

runs:
  using: composite
  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6.0.1
      with:
        cache-read-only: false

    - name: Mark Gradle as Executable
      shell: bash
      run: chmod +x gradlew
