name: Setup Gradle

runs:
    using: composite
    steps:
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4
          with:
              cache-disabled: ${{ !env.ACT }}
              cache-read-only: false

        - name: Mark Gradle as Executable
          shell: bash
          run: chmod +x ./gradlew
