on:
    workflow_call:
        inputs:
            version:
                type: string
                required: true
            name:
                type: string
                required: true
            logo:
                type: string
                required: true
            color:
                type: string
                required: true

jobs:
    announce-discord:
        name: Announce to Discord - v${{ inputs.version }}
        runs-on: ubuntu-latest
        steps:
            - name: Announce to Discord
              env:
                  MOD_NAME: ${{ inputs.name }}
              run: |
                JSON=$(cat <<EOF
                {
                    "content": "",
                    "embeds": [
                        {
                            "title": "${{ env.MOD_NAME }} updated to v${{ inputs.version }}!",
                            "footer": {
                            "text": "ApexStudios",
                            "icon_url": "https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/apexstudios/Logo.png"
                        },
                        "thumbnail": { "url": "${{ inputs.logo }}" },
                        "color": ${{ inputs.color }}
                        }
                    ],
                    "username": "ApexStudios",
                    "avatar_url": "https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/apexstudios/Logo.png"
                }
                EOF
                )
                  
                curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" -H "Content-Type: application/json" -H "Accept: application/json" -d "$JSON"
