on:
    workflow_call:
        inputs:
            version:
                type: string
                required: true
            name:
                type: string
                required: true
            logo:
                type: string
                required: true
            color:
                type: string
                required: true

jobs:
    announce-discord:
        name: Announce to Discord - v${{ inputs.version }}
        runs-on: apexstudios
        steps:
            - name: Announce to Discord
              run: |
                  RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
                      "content": "",
                      "embeds": [
                          {
                              "author": { "name": "${{ inputs.name }}" },
                              "title": "${{ inputs.name }} updated to v${{ inputs.version }}!",
                              "footer": {
                                  "text": "ApexStudios",
                                  "icon_url": "https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/apexstudios/Logo.png"
                              },
                              "thumbnail": { "url": "${{ inputs.logo }}" },
                              "color": ${{ inputs.color }},
                              "timestamp": "$(date +"%Y-%m-%dT%H:%M:%SZ")"
                          }
                      ],
                      "username": "ApexStudios",
                      "avatar_url": "https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/apexstudios/Logo.png"
                  }' ${{ secrets.DISCORD_WEBHOOK_URL }})
                  echo "Discord WebHook response: $RESPONSE"
