name: Build PR

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-vendor:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build-pr:
    name: Build PR
    runs-on: apexstudios
    if: success()
    steps:
      - name: Checkout Repository
        uses: ApexStudios-Dev/.github/actions/checkout@better-workflow # TODO: Change to 'master'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-vendor }}

      - name: Setup Gradle
        uses: ApexStudios-Dev/.github/actions/setup-gradle@better-workflow # TODO: Change to 'master'

      - name: Run with Gradle
        run: ./gradlew :build
        env:
          VERSION: ${{ inputs.version }}
