name: Build

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-vendor:
        required: true
        type: string
    outputs:
      version:
        description: Generated version
        value: ${{ jobs.generate-vars.outputs.version }}
      timestamp:
        description: Generated timestamp
        value: ${{ jobs.generate-vars.outputs.timestamp }}

jobs:
  generate-vars:
    name: Generate Vars
    uses: ApexStudios-Dev/.github/.github/workflows/_generate-vars.yml@workflow-refactor
    secrets: inherit

  build:
    name: Build
    needs: generate-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: ApexStudios-Dev/.github/actions/checkout@workflow-refactor

      - name: Setup Java
        uses: ApexStudios-Dev/.github/actions/setup-java@workflow-refactor
        with:
          java-version: ${{ inputs.java-version }}
          java-vendor: ${{ inputs.java-vendor }}

      - name: Setup Gradle
        uses: ApexStudios-Dev/.github/actions/setup-gradle@workflow-refactor

      - name: Build with Gradle
        run: ./gradlew :build
        env:
          VERSION: ${{ needs.generate-vars.outputs.version }}
