name: Generate Version

on:
  workflow_call:

jobs:
  generate-version:
    name: Generate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: ApexStudios-Dev/.github/actions/checkout@better-workflow # TODO: Change to 'master'

      - name: Generate version
        id: version
        uses: ApexStudios-Dev/.github/actions/version@better-workflow # TODO: Change to 'master'
