name: Publish to CurseForge

on:
    workflow_call:
        inputs:
            display_name:
                type: string
                required: true
            version:
                type: string
                required: true
            release_type:
                type: string
                required: true
            artifact_id:
                type: string
                required: true
            curseforge_id:
                type: string
                required: true
        outputs:
            download:
                value: ${{ jobs.publish-curseforge.outputs.download }}

jobs:
    publish-curseforge:
        name: Publish to CurseForge
        runs-on: ubuntu-latest
        outputs:
            download: ${{ steps.publish.outputs.curseforge_url }}
        steps:
            - name: Delete old artifacts dir
              shell: bash
              run: rm -rf ./build/curseforge-libs/

            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: artifacts
                  path: ./build/curseforge-libs/

            - name: Validate artifact exists
              shell: bash
              run: if [ ! -f "./build/curseforge-libs/${{ inputs.artifact_id }}-${{ inputs.version }}.jar" ]; then exit 1; fi

            - name: Publish to CurseForge
              if: ${{ !env.ACT }}
              id: publish
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  curseforge-id: ${{ inputs.curseforge_id }}
                  curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

                  files: ./build/curseforge-libs/${{ inputs.artifact_id }}-${{ inputs.version }}.jar
                  name: ${{ inputs.display_name }}-${{ inputs.version }}
                  version: ${{ inputs.version }}
                  version-type: ${{ inputs.release_type }}
                  changelog: ""
                  loaders: neoforge
