name: Publish Maven

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-vendor:
        required: true
        type: string
      use-self-runner:
        required: true
        type: boolean
        default: true
      publish-task:
        required: true
        type: string
    outputs:
      version:
        description: Generated version
        value: ${{ jobs.generate-vars.outputs.version }}
      timestamp:
        description: Generated timestamp
        value: ${{ jobs.generate-vars.outputs.timestamp }}
      runner:
        description: Determined runner
        value: ${{ jobs.generate-vars.outputs.runner }}

jobs:
  generate-vars:
    name: Generate Vars
    uses: ApexStudios-Dev/.github/.github/workflows/_generate-vars.yml@master
    secrets: inherit
    with:
      use-self-runner: ${{ inputs.use-self-runner }}

  publish-maven:
    name: Publish Maven
    needs: generate-vars
    runs-on: ${{ needs.generate-vars.outputs.runner }}
    steps:
      - name: Checkout Repository
        uses: ApexStudios-Dev/.github/actions/checkout@master

      - name: Setup Java
        uses: ApexStudios-Dev/.github/actions/setup-java@master
        with:
          java-version: ${{ inputs.java-version }}
          java-vendor: ${{ inputs.java-vendor }}

      - name: Setup Gradle
        uses: ApexStudios-Dev/.github/actions/setup-gradle@master
        with:
          use-gradle-cache: ${{ !inputs.use-self-runner }}

      - name: Run with Gradle
        run: ./gradlew ${{ inputs.publish-task }}
        env:
          VERSION: ${{ needs.generate-vars.outputs.version }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
