name: Publish PR artifact

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: true
      java-vendor:
        type: string
        required: true
      mod-version:
        type: string
        required: true

jobs:
  publish-pr-artifact:
    name: Publish PR artifact
    runs-on: apexstudios
    steps:
      - name: Checkout repository
        uses: ApexStudios-Dev/.github/actions/checkout@better-workflow # TODO: Change to master before merging

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-vendor }}

      - name: Setup Gradle
        uses: ApexStudios-Dev/.github/actions/setup-gradle@better-workflow # TODO: Change to master before merging

      - name: Generate data with Gradle
        run: ./gradlew :publishReleasePublicationToApexStudios-PrivateRepository
        env:
          VERSION: ${{ inputs.mod-version }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
