name: Publish Library

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-vendor:
        required: true
        type: string
      publish-task:
        required: true
        type: string
      display-name:
        required: true
        type: string
      color:
        required: true
        type: string

jobs:
  generate-vars:
    name: Generate Vars
    uses: ApexStudios-Dev/.github/.github/workflows/_generate-vars.yml@master
    secrets: inherit

  publish-maven:
    name: Publish Maven
    uses: ApexStudios-Dev/.github/.github/workflows/_publish-maven.yml@master
    needs: generate-vars
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}
      java-vendor: ${{ inputs.java-vendor }}
      version: ${{ needs.generate-vars.outputs.version }}
      publish-task: ${{ inputs.publish-task }}

  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [ generate-vars, publish-maven ]
    if: success()
    steps:
      - name: Send Announcement to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: ${{ inputs.display-name }} updated to v${{ needs.generate-vars.outputs.version }}!
          embed-color: ${{ inputs.color }}
          embed-timestamp: ${{ needs.generate-vars.outputs.timestamp }}
          avatar-url: 'https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/apexstudios/Logo.png'
          username: ApexStudios
          embed-footer-text: ApexStudios
          embed-footer-icon-url: 'https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/apexstudios/Logo.png'
