name: Publish Library

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-vendor:
        required: true
        type: string
      publish-task:
        required: true
        type: string
      display-name:
        required: true
        type: string
      color:
        required: true
        type: string
      use-self-runner:
        required: true
        type: boolean
        default: true

jobs:
  publish-maven:
    name: Publish Maven
    uses: ApexStudios-Dev/.github/.github/workflows/_publish-maven.yml@master
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}
      java-vendor: ${{ inputs.java-vendor }}
      use-self-runner: ${{ inputs.use-self-runner }}
      publish-task: ${{ inputs.publish-task }}

  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: publish-maven
    if: success()
    steps:
      - name: Send Announcement to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: ${{ inputs.display-name }} updated to v${{ needs.publish-maven.outputs.version }}!
          embed-color: ${{ inputs.color }}
          embed-timestamp: ${{ needs.publish-maven.outputs.timestamp }}
          avatar-url: 'https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/apexstudios/Logo.png'
          username: ApexStudios
          embed-footer-text: ApexStudios
          embed-footer-icon-url: 'https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/apexstudios/Logo.png'
