name: Publish to Platforms

on:
    workflow_call:
        inputs:
            version:
                type: string
                required: true
            build_timestamp:
                type: string
                required: true
            display_name:
                type: string
                required: true
            logo_url:
                type: string
                required: true
            color:
                type: number
                required: true
            release_type:
                type: string
                required: false
                default: release
            artifact_id:
                type: string
                required: true
            curseforge_id:
                type: string
                required: false
            modrinth_id:
                type: string
                required: false

jobs:
    publish-curseforge:
        name: Publish to CurseForge
        uses: ApexStudios-Dev/.github/.github/workflows/_publish-curseforge.yml@master
        if: inputs.curseforge_id
        secrets: inherit
        with:
            display_name: ${{ inputs.display_name }}
            version: ${{ inputs.version }}
            release_type: ${{ inputs.release_type }}
            artifact_id: ${{ inputs.artifact_id }}
            curseforge_id: ${{ inputs.curseforge_id }}

    publish-modrinth:
        name: Publish to Modrinth
        uses: ApexStudios-Dev/.github/.github/workflows/_publish-modrinth.yml@master
        if: inputs.modrinth_id
        secrets: inherit
        with:
            display_name: ${{ inputs.display_name }}
            version: ${{ inputs.version }}
            release_type: ${{ inputs.release_type }}
            artifact_id: ${{ inputs.artifact_id }}
            modrinth_id: ${{ inputs.modrinth_id }}

    notify-discord:
        name: Send Announcement to Discord
        needs: [ publish-curseforge, publish-modrinth ]
        if: success()
        runs-on: ubuntu-latest
        steps:
            - name: Send Announcement to Discord
              uses: ApexStudios-Dev/.github/actions/discord-version-notify@master
              with:
                  webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  display_name: ${{ inputs.display_name }}
                  version: ${{ inputs.version }}
                  logo_url: ${{ inputs.logo_url }}
                  color: ${{ inputs.color }}
                  build_timestamp: ${{ inputs.build_timestamp }}
                  curseforge_url: ${{ needs.publish-curseforge.outputs.download }}
                  modrinth_url: ${{ needs.publish-modrinth.outputs.download }}
