name: Publish to Modrinth

on:
    workflow_call:
        inputs:
            display_name:
                type: string
                required: true
            version:
                type: string
                required: true
            release_type:
                type: string
                required: true
            artifact_id:
                type: string
                required: true
            modrinth_id:
                type: string
                required: true
        outputs:
            modrinth_download:
                value: ${{ jobs.publish-modrinth.outputs.download }}

jobs:
    publish-modrinth:
        name: Publish to Modrinth
        runs-on: ubuntu-latest
        outputs:
            download: ${{ steps.publish.outputs.modrinth_url }}
        steps:
            - name: Delete old artifacts dir
              run: rm -rf ./build/modrinth-libs/

            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: artifacts
                  path: ./build/modrinth-libs/

            - name: Validate artifact exists
              run: if [ ! -f "./build/modrinth-libs/${{ inputs.artifact_id }}-${{ inputs.version }}.jar" ]; then exit 1; fi

            - name: Publish to Modrinth
              if: ${{ !env.ACT }}
              id: publish
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-id: ${{ inputs.modrinth_id }}
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

                  files: ./build/modrinth-libs/${{ inputs.artifact_id }}-${{ inputs.version }}.jar
                  name: ${{ inputs.display_name }}-${{ inputs.version }}
                  version: ${{ inputs.version }}
                  version-type: ${{ inputs.release_type }}
                  changelog: ""
                  loaders: neoforge
