name: Publish Maven

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-vendor:
        required: true
        type: string
      version:
        required: true
        type: string
      publish-task:
        required: true
        type: string

jobs:
  publish-maven:
    name: Publish Maven
    runs-on: apexstudios
    steps:
      - name: Checkout Repository
        uses: ApexStudios-Dev/.github/actions/checkout@master

      - name: Setup Java
        uses: ApexStudios-Dev/.github/actions/setup-java@master
        with:
          java-version: ${{ inputs.java-version }}
          java-vendor: ${{ inputs.java-vendor }}

      - name: Setup Gradle
        uses: ApexStudios-Dev/.github/actions/setup-gradle@master

      - name: Run with Gradle
        run: ./gradlew ${{ inputs.publish-task }}
        env:
          VERSION: ${{ inputs.version }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
