on:
    workflow_call:
        inputs:
            java_version:
                type: string
                required: true
            java_vendor:
                type: string
                required: true
            version:
                type: string
                required: true
            artifact_id:
                type: string
                default: artifacts
            modrinth_id:
                type: string
                required: true
            release_type:
                type: string
                required: true

jobs:
    publish-modrinth:
        name: Publish Modrinth - v${{ inputs.version }}
        runs-on: apexstudios
        steps:
            - name: Delete old artifacts dir
              run: rm -rf ./build/modrinth-libs/

            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: ${{ inputs.artifact_id }}
                  path: ./build/modrinth-libs/

            - name: Publish Modrinth
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-id: EjjiYArZ
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

                  files: ./build/modrinth-libs/*[!(sources|data)].jar
                  name: ${{ inputs.name }}-${{ inputs.version }}
                  version: ${{ inputs.version }}
                  version-type: ${{ inputs.release_type }}
                  changelog: ""
                  loaders: neoforge
                  java: ${{ inputs.java_version }}
