on:
    workflow_call:
        inputs:
            java_version:
                type: string
                required: true
            java_vendor:
                type: string
                required: true
            version:
                type: string
                required: true

jobs:
    publish-maven:
        name: Publish Maven - v${{ inputs.version }}
        runs-on: apexstudios
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: ${{ inputs.java_vendor }}
                  java-version: ${{ inputs.java_version }}

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4
              with:
                  cache-disabled: ${{ ! env.ACT }}
                  cache-read-only: false

            - name: Mark Gradle as Executable
              run: chmod +x ./gradlew

            - name: Publish Maven
              if: ${{ ! env.ACT }}
              run: ./gradlew :publish
              env:
                  VERSION: ${{ inputs.version }}
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
