on:
    workflow_call:
        inputs:
            java_version:
                type: string
                required: true
            java_vendor:
                type: string
                required: true
            version:
                type: string
                required: true
            artifact_id:
                type: string
                default: artifacts
            curseforge_id:
                type: string
                required: true
            release_type:
                type: string
                required: true
            name:
                type: string
                required: true

jobs:
    publish-curseforge:
        name: Publish CurseForge - v${{ inputs.version }}
        runs-on: apexstudios
        steps:
            - name: Delete old artifacts dir
              run: rm -rf ./build/curseforge-libs/

            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: ${{ inputs.artifact_id }}
                  path: ./build/curseforge-libs/

            - name: Publish CurseForge
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  curseforge-id: ${{ inputs.curseforge_id }}
                  curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

                  files: ./build/curseforge-libs/*[!(sources|data)].jar
                  name: ${{ inputs.name }}-${{ inputs.version }}
                  version: ${{ inputs.version }}
                  version-type: ${{ inputs.release_type }}
                  changelog: ""
                  loaders: neoforge
                  java: ${{ inputs.java_version }}
