name: Upload PR

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-vendor:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  upload-pr:
    name: Upload PR
    runs-on: apexstudios
    steps:
      - name: Checkout Repository
        uses: ApexStudios-Dev/.github/actions/checkout@master

      - name: Setup Java
        uses: ApexStudios-Dev/.github/actions/setup-java@master
        with:
          java-version: ${{ inputs.java-version }}
          java-vendor: ${{ inputs.java-vendor }}

      - name: Setup Gradle
        uses: ApexStudios-Dev/.github/actions/setup-gradle@master

      - name: Upload PR
        uses: neoforged/action-pr-publishing/upload@v1
        env:
          VERSION: ${{ inputs.version }}
