name: Build PR

on:
    workflow_call:

jobs:
    build-pr:
        name: Build PR
        runs-on: apexstudios
        steps:
            - name: Checkout Repository
              id: checkout
              uses: ApexStudios-Dev/.github/actions/checkout@master

            - name: Setup Java
              uses: ApexStudios-Dev/.github/actions/setup-java@master

            - name: Setup Gradle
              uses: ApexStudios-Dev/.github/actions/setup-gradle@master

            - name: Build with Gradle
              shell: bash
              run: ./gradlew :build
              env:
                  VERSION: ${{ steps.checkout.outputs.version }}
