on:
    workflow_call:
        inputs:
            java_version:
                type: string
                default: 17
            java_vendor:
                type: string
                default: temurin
            artifact_id:
                type: string
                required: true

jobs:
    get-vars:
        name: Get Variables
        runs-on: apexstudios
        outputs:
            version: ${{ steps.version.outputs.version }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                fetch-tags: true

            - name: Determine version
              uses: paulhatch/semantic-version@v5.4.0
              id: version
              with:
                change_path: "./"
                version_format: "${major}.${minor}.${patch}"
                search_commit_body: true
                bump_each_commit: true

    # test:
    #     needs: [ get-vars ]
    #     uses: ApexStudios-Dev/.github/.github/workflows/_tests.yml@master
    #     secrets: inherit
    #     with:
    #         java_version: ${{ inputs.java_version }}
    #         java_vendor: ${{ inputs.java_vendor }}
    #         version: ${{ needs.get-vars.outputs.version }}

    build:
        needs: [ get-vars ]
        uses: ApexStudios-Dev/.github/.github/workflows/_build.yml@master
        secrets: inherit
        with:
            java_version: ${{ inputs.java_version }}
            java_vendor: ${{ inputs.java_vendor }}
            version: ${{ needs.get-vars.outputs.version }}
            artifact_id: ${{ inputs.artifact_id }}
