name: Build PR

on:
    workflow_call:

jobs:
    build-pr:
        name: Build PR
        runs-on: apexstudios
        steps:
            - name: Checkout Repository
              id: checkout
              uses: ApexStudios-Dev/.github/actions/checkout@master

            - name: Setup Java
              uses: ApexStudios-Dev/.github/actions/setup-java@master

            - name: Build with Gradle
              uses: ApexStudios-Dev/.github/actions/run-gradle@master
              with:
                  setup: true
                  tasks: :build
              env:
                  VERSION: ${{ steps.checkout.outputs.version }}
