name: Generate Changelog

on:
  workflow_call:
    inputs:
      tag_current:
        type: string
        required: true
      tag_previous:
        type: string
        required: true

jobs:
  # Generate changelog
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0

      - name: Clone Changelog Template Repository
        uses: actions/checkout@v3.1.0
        with:
          repository: ApexStudios-Dev/.github
          path: ./Templates

      - name: Unshallow Repository
        run: git fetch --prune --unshallow

      - name: Copy templates to expected location
        run: |
          cp ./Templates/.github/changelog.json ./.github/changelog.json
          cp ./Templates/.github/changelog.mustache ./.github/changelog.mustache

      - name: Generate changelog
        uses: jimschubert/beast-changelog-action@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          CONFIG_LOCATION: .github/changelog.json
          FROM: ${{ inputs.tag_previous }}
          TO: ${{ inputs.tag_current }}
          OUTPUT: .github/CHANGELOG.md

      - name: View Changelog
        run: cat .github/CHANGELOG.md

      - name: Upload Changelog
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: .github/CHANGELOG.md
