name: Publish Project

on:
  workflow_call:
    secrets:
      # We should have maven publication in here too
      # See compile to-do marker as why it is done there and not here
      MODRINTH_TOKEN:
        required: true
        description: Auth token used to publish to Modrinth
      CURSEFORGE_TOKEN:
        required: true
        description: Auth token used to publish to CurseForge
    inputs:
      mod_name:
        type: string
        required: true
      mod_version:
        type: string
        required: true
      mod_curseforge_id:
        type: string
        required: true
      mod_modrinth_id:
        type: string
        required: true
      mod_release_type:
        type: string
        required: true
      minecraft_version:
        type: string
        required: true
      tag_current:
        type: string
        required: true

jobs:
  # Publish jars to various sources
  publish:
    name: Publish Mod
    runs-on: ubuntu-latest

    steps:
      - name: Download Changelog
        uses: actions/download-artifact@v3
        with:
          name: changelog
          path: .github

      - name: Download Compiled Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: ./build/libs

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ${{ needs.vars.outputs.mod_modrinth_id }}
          modrinth-featured: true
          modrinth-unfeature: intersection
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: ${{ needs.vars.outputs.mod_curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-tag: ${{ inputs.tag_current }}
          github-generate-changelog: false
          github-draft: false
          github-prerelease: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: ./build/libs/!(*-@(deobf|slim|sources|javadocs|all)).jar
          files-secondary: ./build/libs/*-@(deobf|slim|sources|javadocs|all).jar

          changelog-file: ./.github/CHANGELOG.md

          name: ${{ inputs.mod_name }} - v${{ inputs.mod_version }} for Minecraft ${{ inputs.minecraft_version }}
          version: ${{ inputs.mod_version }}
          version-type: ${{ inputs.mod_release_type }}
          version-resolver: latest

          loaders: forge
          game-versions: ${{ inputs.minecraft_version }}
          java: 17

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
