name: Generate Changelog

on:
  workflow_call:

jobs:
  # Gather variables used throughout the workflow
  vars:
    name: Gather workflow variables
    runs-on: ubuntu-latest

    outputs:
      tag_current: ${{ steps.tag_current.outputs.tag }}
      tag_previous: ${{ steps.tag_previous.outputs.tag }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Unshallow Repository
        run: git fetch --prune --unshallow

      - name: Find Current Tag
        id: tag_current
        uses: jimschubert/query-tag-action@v1
        with:
          include: v*
          commit-ish: '@'
          skip-unshallow: true

      - name: Find Previous Tag
        id: tag_previous
        uses: jimschubert/query-tag-action@v1
        with:
          include: v*
          exclude: ${{ steps.tag_current.outputs.tag }}
          skip-unshallow: true

      - name: View Variables
        run: |
          echo "'tag_current': => '${{ steps.tag_current.outputs.tag }}'"
          echo "'tag_previous': => '${{ steps.tag_previous.outputs.tag }}'"

  # Generate changelog
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    needs: [ vars ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Changelog Template Repository
        uses: actions/checkout@v2
        with:
          repository: ApexStudios-Dev/.github
          path: ./Templates

      - name: Unshallow Repository
        run: git fetch --prune --unshallow

      - name: Copy templates to expected location
        run: |
          cp ./Templates/.github/changelog.json ./.github/changelog.json
          cp ./Templates/.github/changelog.mustache ./.github/changelog.mustache

      - name: Generate changelog
        uses: jimschubert/beast-changelog-action@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          CONFIG_LOCATION: .github/changelog.json
          FROM: ${{ needs.vars.outputs.tag_previous }}
          TO: ${{ needs.vars.outputs.tag_current }}
          OUTPUT: .github/CHANGELOG.md

      - name: View Changelog
        run: cat .github/CHANGELOG.md

      - name: Upload Changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: .github/CHANGELOG.md