on:
    workflow_call:
        inputs:
            java_version:
                type: string
                default: 17
            java_vendor:
                type: string
                default: temurin
            curseforge_id:
                type: string
                required: true
#            modrinth_id:
#                type: string
#                required: true
            release_type:
                type: string
                default: release
            name:
                type: string
                required: true
            logo:
                type: string
                required: true
            color:
                type: string
                required: true

jobs:
    get-vars:
        name: Get Variables
        runs-on: apexstudios
        outputs:
            version: ${{ steps.version.outputs.version }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                fetch-tags: true

            - name: Determine version
              uses: paulhatch/semantic-version@v5.4.0
              id: version
              with:
                change_path: "./"
                version_format: "${major}.${minor}.${patch}"
                search_commit_body: true
                bump_each_commit: true

#    test:
#         needs: [ get-vars ]
#         uses: ApexStudios-Dev/.github/.github/workflows/_test.yml@master
#         secrets: inherit
#         with:
#             java_version: ${{ inputs.java_version }}
#             java_vendor: ${{ inputs.java_vendor }}
#             version: ${{ needs.get-vars.outputs.version }}

    build:
         needs: [ get-vars ]
         uses: ApexStudios-Dev/.github/.github/workflows/_build.yml@master
         secrets: inherit
         with:
             java_version: ${{ inputs.java_version }}
             java_vendor: ${{ inputs.java_vendor }}
             version: ${{ needs.get-vars.outputs.version }}

    publish-maven:
#        needs: [ get-vars, test, build ]
        needs: [ get-vars, build ]
        if: success()
        uses: ApexStudios-Dev/.github/.github/workflows/_publish-maven.yml@master
        secrets: inherit
        with:
            java_version: ${{ inputs.java_version }}
            java_vendor: ${{ inputs.java_vendor }}
            version: ${{ needs.get-vars.outputs.version }}

    publish-curseforge:
#        needs: [ get-vars, test, build ]
        needs: [ get-vars, build ]
        if: success()
        uses: ApexStudios-Dev/.github/.github/workflows/_publish-curseforge.yml@master
        secrets: inherit
        with:
            java_version: ${{ inputs.java_version }}
            java_vendor: ${{ inputs.java_vendor }}
            version: ${{ needs.get-vars.outputs.version }}
            curseforge_id: ${{ inputs.curseforge_id }}
            release_type: ${{ inputs.release_type }}

#    publish-modrinth:
##        needs: [ get-vars, test, build ]
#        needs: [ get-vars, build ]
#        if: success()
#        uses: ApexStudios-Dev/.github/.github/workflows/_publish-modrinth.yml@master
#        secrets: inherit
#        with:
#            java_version: ${{ inputs.java_version }}
#            java_vendor: ${{ inputs.java_vendor }}
#            version: ${{ needs.get-vars.outputs.version }}
#            modrinth_id: ${{ inputs.modrinth_id }}
#            release_type: ${{ inputs.release_type }}

    announce-discord:
#        needs: [ get-vars, publish-maven, publish-curseforge, publish-modrinth ]
        needs: [ get-vars, publish-maven, publish-curseforge ]
        if: success()
        uses: ApexStudios-Dev/.github/.github/workflows/_announce-discord.yml@master
        secrets: inherit
        with:
            version: ${{ needs.get-vars.outputs.version }}
            name: ${{ inputs.name }}
            logo: ${{ inputs.logo }}
            color: ${{ inputs.color }}
