name: Publish Mod

on:
    workflow_call:
        inputs:
            display_name:
                type: string
                required: true
            logo_url:
                type: string
                required: true
            color:
                type: number
                required: true
            release_type:
                type: string
                required: false
                default: release
            artifact_id:
                type: string
                required: true
            curseforge_id:
                type: string
                required: false
            modrinth_id:
                type: string
                required: false
            maven:
                type: boolean
                required: false
                default: true

jobs:
    build:
        name: Build
        runs-on: apexstudios
        outputs:
            timestamp: ${{ steps.timestamp.outputs.output }}
            version: ${{ steps.checkout.outputs.version }}
        steps:
            - name: Checkout Repository
              id: checkout
              uses: ApexStudios-Dev/.github/actions/checkout@master

            - name: Setup Java
              uses: ApexStudios-Dev/.github/actions/setup-java@master

            - name: Build with Gradle
              uses: ApexStudios-Dev/.github/actions/run-gradle@master
              with:
                  setup: true
                  tasks: :build
              env:
                  VERSION: ${{ steps.checkout.outputs.version }}

            - name: Generate Timestamp
              id: timestamp
              shell: bash
              run: echo "output=$(date --iso-8601=seconds)" >> $GITHUB_OUTPUT

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: artifacts
                  path: ./build/libs/*.jar
                  if-no-files-found: error

    publish-maven:
        name: Publish to Maven
        needs: build
        if: inputs.maven
        uses: ApexStudios-Dev/.github/.github/workflows/_publish-maven.yml@master
        secrets: inherit

    publish-platforms:
        name: Publish to Platforms
        needs: [ build, publish-maven ]
        if: success()
        uses: ApexStudios-Dev/.github/.github/workflows/_publish-mod-platforms.yml@master
        secrets: inherit
        with:
            version: ${{ needs.build.outputs.version }}
            build_timestamp: ${{ needs.build.outputs.build_timestamp }}
            display_name: ${{ inputs.display_name }}
            logo_url: ${{ inputs.logo_url }}
            color: ${{ inputs.color }}
            release_type: ${{ inputs.release_type }}
            artifact_id: ${{ inputs.artifact_id }}
            curseforge_id: ${{ inputs.curseforge_id }}
            modrinth_id: ${{ inputs.modrinth_id }}
