name: Publish PR

on:
    workflow_call:

jobs:
  publish-pr:
        name: Publish PR
        runs-on: apexstudios
        steps:
            - name: Checkout Repository
              id: checkout
              uses: ApexStudios-Dev/.github/actions/checkout@master

            - name: Setup Java
              uses: ApexStudios-Dev/.github/actions/setup-java@master

            - name: Setup Gradle
              uses: ApexStudios-Dev/.github/actions/setup-gradle@master

            - name: Publish with Gradle
              run: ./gradlew :publishReleasePublicationToApexStudios-PrivateRepository
              env:
                  VERSION: ${{ steps.checkout.outputs.version }}
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

            - name: Comment on PR
              uses: thollander/actions-comment-pull-request@v3
              with:
                message: "Successfully published v`${{ steps.checkout.outputs.version }}` under the repo `https://maven.apexstudios.dev/private`"
