on:
    workflow_call:
        inputs:
            java_version:
                type: string
                required: true
                default: 17
            java_vendor:
                type: string
                required: true
                default: temurin
        secrets:
            MAVEN_USERNAME:
                required: true
            MAVEN_PASSWORD:
                required: true

jobs:
    datagen:
        uses: ./.github/workflows/datagen.yml

    publish:
        needs: [ datagen ]
        uses: ./.github/workflows/publish.yml
        secrets:
            MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}