name: Test Production Server

on:
  workflow_call:
    inputs:
      neoforge_version:
        description: Version of NeoForge to install
        type: string
        required: true
      java_version:
        description: Version of Java to install
        type: string
        required: false
        default: 21
      install_artifacts:
        description: Artifacts to be installed into the servers 'mods' directory
        type: string
        required: true
        default: production-artifacts

jobs:
  test-production-server:
    name: Test Production Server
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: ApexStudios-Dev/.github/actions/setup-java@master
        with:
          version: ${{ inputs.java_version }}

      - name: Download NeoForge Installer
        run: |
          wget "https://maven.neoforged.net/releases/net/neoforged/neoforge/${{ inputs.neoforge_version }}/neoforge-${{ inputs.neoforge_version }}-installer.jar" -O "neoforge-installer.jar"
          java -jar neoforge-installer.jar --install-server

      - name: Prepare Environment
        run: |
          touch ./eula.txt
          echo "eula=true" >> ./eula.txt
          rm -rf ./mods

      - name: Install Mods
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.install_artifacts }}
          path: ./mods

      - name: Run Production Server
        run: ./run.sh
        env:
          # neoforge uses this env var to shutdown server after first tick
          # neodevs internal 'test-production-server' tasks fail if this file does not exist
          # after server has ran, we mimic the same functionality below
          # https://github.com/neoforged/NeoForge/blob/ea51140336afccf0495a31a6e0e795ca702d361a/src/main/java/net/neoforged/neoforge/common/util/SelfTest.java
          NEOFORGE_DEDICATED_SERVER_SELFTEST: ${{ github.workspace }}/server_self_test.txt

      - name: Cleanup Environment
        if: always()
        run: rm -f ./eula.txt

      - name: Upload Environment
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: environment
          path: ./

      # kill the workflow if self test file was not generated
      # this could mean server ran into some error/hard crashed before neos self test could shut it down
      - name: Validate Self Test
        run: if [ ! -f "./server_self_test.txt" ]; then exit 1; fi
